services:
  # Backend API service
  - type: web
    name: chappyv
    runtime: node
    plan: free
    rootDirectory: backend
    buildCommand: npm ci && npm i typescript --no-save && npm run build && ls -la dist/
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://chappy-frontend.onrender.com

  # Frontend static site
  - type: static
    name: chappy-frontend
    rootDirectory: frontend
    buildCommand: cd backend && npm ci --production && npm i typescript --no-save && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://chappyv.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html